### ISSUE TITLE
As an Admin, I want uploaded photos to be compressed, so that less Google Drive storage space is utilized

### ISSUE THREAD

**Issue by AlexanderChiuy** [involveMINT/iMPublic#15]
**Conversation**
Initial idea → Currently POI photos are stored in a Google Drive. As application grows the storage consumed by storing full-sized photos could balloon, this is likely something that will help keep costs down.

**Confirmation**
Manual test to confirm that size of photos is an acceptable size, so that the GDrive will not fill up too quickly

**Comment by tylowe-labs** [comment]
I believe the direction we are going with this is to find a library that can resize the images s.t that fit better on the activity feed AND take up less space

**Comment by tylowe-labs** [comment]
As an update, we are using "Resize Images" on Firebase to resize inputted images (no codebase changes)
