### ISSUE TITLE
New user first time login required popup can be closed

### ISSUE THREAD

**Issue by QuinnNTonic** [involveMINT/iMPublic#160]
## Repro Steps

<div>It was found that when a new user logs in/signs up for the first time, the popup screens that enable the user to set their role could exit and leave the user with an empty profile.&nbsp; </div><div><br> </div><div><span style="color:rgb(29, 28, 29);font-family:Slack-Lato, Slack-Fractions, appleLogo, sans-serif;font-size:15px;text-align:left;display:inline !important;">From Dan: &quot;On first time login People should not be able to click out of the modal that asks you which role you want to be. They just get a menu that says no active profile&quot;</span><br> </div>

May be related to: https://github.com/involveMINT/iMPublic/issues/281

**Comment by QuinnNTonic** [comment]
[Original Work Item URL](https://dev.azure.com/involvemint/involveMINT/_workitems/edit/537)


<details><summary>Original Work Item Details</summary><p>


| Created date | Created by | Changed date | Changed By | Assigned To | State | Type | Area Path | Iteration Path|
|---|---|---|---|---|---|---|---|---|
| 05/12/2022 07:11:26 | Ryan McAndrew | 05/19/2024 22:42:08 | info |  | New | Bug | involveMINT\involveMINT | involveMINT\72 |




</p></details>


<details><summary>Original Work Item JSON</summary><p>

```json
{
  "fields": {
    "Microsoft.VSTS.Common.Priority": 4,
    "Microsoft.VSTS.Common.StackRank": 997991993,
    "Microsoft.VSTS.Common.StateChangeDate": "05/12/2022 07:11:26",
    "System.AssignedTo": {
      "displayName": ""
    },
    "System.BoardColumn": "New",
    "System.BoardColumnDone": False,
    "System.ChangedBy": {
      "displayName": "info"
    },
    "System.ChangedDate": "05/19/2024 22:42:08",
    "System.CommentCount": 0,
    "System.CreatedBy": {
      "displayName": "Ryan McAndrew"
    },
    "System.CreatedDate": "05/12/2022 07:11:26",
    "System.Id": 537,
    "System.Reason": "New",
    "System.Rev": 11,
    "System.RevisedDate": "01/01/9999 00:00:00",
    "System.State": "New",
    "System.TeamProject": "involveMINT",
    "System.Title": "New user first time login required popup can be closed",
    "System.WorkItemType": "Bug",
    "WEF_F54671B39AF54036B4485F04394D6594_Kanban.Column": "New",
    "WEF_F54671B39AF54036B4485F04394D6594_Kanban.Column.Done": False,
    "WEF_F54671B39AF54036B4485F04394D6594_System.ExtensionMarker": True
  },
  "id": 537,
  "relations": [
    {
      "attributes": {
        "id": ,
        "name": "Parent",
        "resourceCreatedDate": "",
        "resourceModifiedDate": "",
        "resourceSize": ,
        "revisedDate": ""
      },
      "rel": "System.LinkTypes.Hierarchy-Reverse",
      "url": "https://dev.azure.com/involvemint/1853e4bf-a341-4c37-98f5-57387729b589/_apis/wit/workItems/533"
    },
],
  "rev": 11,
  "url": "https://dev.azure.com/involvemint/1853e4bf-a341-4c37-98f5-57387729b589/_apis/wit/workItems/537"
}

```
</p></details>

**Comment by involve-MINT** [comment]
@QuinnNTonic do we know where the modal popup asking user to select their role lives?

**Comment by b3nkang** [comment]
@involve-MINT not going to be able to get to this this week so if it's urgent I would recommend re-assigning it, apologies - sunk a lot of time into the other ticket last night

**Comment by involve-MINT** [comment]
@fogunsan @justpenguins thoughts about reassignment?

**Comment by b3nkang** [comment]
Complete, PR fix [here](https://github.com/involveMINT/iMPublic/pull/320)
