### ISSUE TITLE
Projects are still visible long after their expiration date

### ISSUE THREAD

**Issue by QuinnNTonic** [involveMINT/iMPublic#165]
## System Info

<div>Projects should not be visible after their expiration date. </div>

**Comment by QuinnNTonic** [comment]
[Original Work Item URL](https://dev.azure.com/involvemint/involveMINT/_workitems/edit/610)


<details><summary>Original Work Item Details</summary><p>


| Created date | Created by | Changed date | Changed By | Assigned To | State | Type | Area Path | Iteration Path|
|---|---|---|---|---|---|---|---|---|
| 12/20/2022 20:28:30 | info | 05/19/2024 22:42:44 | info |  | New | Bug | involveMINT\involveMINT | involveMINT\Tech Testing Debt |




</p></details>


<details><summary>Original Work Item JSON</summary><p>

```json
{
  "fields": {
    "Microsoft.VSTS.Common.Priority": 2,
    "Microsoft.VSTS.Common.StackRank": 998004826,
    "Microsoft.VSTS.Common.StateChangeDate": "12/20/2022 20:28:30",
    "System.AssignedTo": {
      "displayName": ""
    },
    "System.BoardColumn": "New",
    "System.BoardColumnDone": False,
    "System.ChangedBy": {
      "displayName": "info"
    },
    "System.ChangedDate": "05/19/2024 22:42:44",
    "System.CommentCount": 0,
    "System.CreatedBy": {
      "displayName": "info"
    },
    "System.CreatedDate": "12/20/2022 20:28:30",
    "System.Id": 610,
    "System.Reason": "New",
    "System.Rev": 5,
    "System.RevisedDate": "01/01/9999 00:00:00",
    "System.State": "New",
    "System.TeamProject": "involveMINT",
    "System.Title": "Projects are still visible long after their expiration date",
    "System.WorkItemType": "Bug",
    "WEF_F54671B39AF54036B4485F04394D6594_Kanban.Column": "New",
    "WEF_F54671B39AF54036B4485F04394D6594_Kanban.Column.Done": False,
    "WEF_F54671B39AF54036B4485F04394D6594_System.ExtensionMarker": True
  },
  "id": 610,
  "relations": [
],
  "rev": 5,
  "url": "https://dev.azure.com/involvemint/1853e4bf-a341-4c37-98f5-57387729b589/_apis/wit/workItems/610"
}

```
</p></details>

**Comment by fogunsan** [comment]
This ticket involved seeing a project created by a ServePartner to private if the end (expiry) date is before the current day. If the project is expired, it is still visible to the ServePartner who made it, showing up as private. For a ChangeMaker looking at the list of available projects in the Serve page, the project will no longer show up.
