### ISSUE TITLE
As a User, I want to be able to flag comments, so that admins can clean up the community feed.

### ISSUE THREAD

**Issue by tylowe-labs** [involveMINT/iMPublic#17]
**Conversation:**
To the right side of each comment in an activity feed, there should be a "..." button that pulls up an option to "flag" a comment and the "reason" for the flag. Reasons can be "inappropriate," "harmful," "derogatory," and "other."

**Confirmation:**
- Unit test that flagging a comment sends an appropriate notification
- Unit test UI has buttons for each of the comments
- Integration test that flagged comments will show up in the database for admins to review in their portal
- User test that users can easily figure out where to flag a comment at
- User test that users are OK with the options for flagging

**Comment by Jareltey** [comment]
Closing this issue since PR has been merged.
