### ISSUE TITLE
Photo aspect ratios are off

### ISSUE THREAD

**Issue by involve-MINT** [involveMINT/iMPublic#270]
When viewing from the marketplace, photos get cut off on the tile standpoint, we need to resize the image appropriately so it fits within the tile.

**Comment by b3nkang** [comment]
When creating a ServePartner project listing or ExchangeProvider storefront on marketplace, the image upload functionality does not work - when in the image upload region (both the storefront image upload and project info), after uploading, a small loading modal pops up and says `upload completed 100%` and then disappears. However, the image upload square turns black continues buffering with a green loading circle indefinitely (even after navigating away and back to the storefront/project). Image does not display and the project listing/marketplace storefront instead shows a blank listing or storefront.

ServePartner examples:

![Image](https://github.com/involveMINT/iMPublic/assets/134336066/5e166d83-d328-46b0-9b8a-52ecf7d62b57)

![Image](https://github.com/involveMINT/iMPublic/assets/134336066/cb2a24ef-b01b-4281-bb30-0b9ec69047e2)



ExchangeProvide examples:

![Image](https://github.com/involveMINT/iMPublic/assets/134336066/67365726-6671-400e-8c84-0dbb18855bd6)

![Image](https://github.com/involveMINT/iMPublic/assets/134336066/8e0d5b93-7b10-4b3f-bcc4-3eb3c5eae63f)

**Comment by b3nkang** [comment]
Fix for the image loading in prev. comment involved replacing `gcp` and `firebaseEnv` in `environment.local.ts` to be hooked up to imPublic instance.

Fix for the images (task itself):

Before:

![Image](https://github.com/involveMINT/iMPublic/assets/134336066/9eac3e5d-ab0d-4c4f-bad6-c2328939712f)


After:

![Image](https://github.com/involveMINT/iMPublic/assets/134336066/84735d14-e67a-4299-ac0f-12fe685badec)

(Identical to behaviour in the `im-image` component)
