### ISSUE TITLE
As a business, when I unlist or make my storefront private, I ALSO want my offers to be unlisted or private accordingly

### ISSUE THREAD

**Issue by involve-MINT** [involveMINT/iMPublic#313]
Offers are eligible to be viewed under marketplace hamburger menu-> spend -> offers tab.

**Comment by fogunsan** [comment]
In the storefront of a business, when making a storefront either unlisted or private, it makes the offers for that storefront unlisted or private, respectively. A user can still go in and manually change an individual offer to make it either private or unlisted as that behaviour is not currently disabled. Changing a storefront back to public from private/unlisted does not affect the status of the offers and thus the offers would retain their prior private/unlisted status.
